- name: install cart
  hosts: cart
  become: yes
  tasks:
  - name: update nodejs version
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y ;

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: user add
    ansible.builtin.user:
    name: roboshop

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the application code
    ansible.builtin.command: https://roboshop-builds.s3.amazonaws.com/cart.zip

  - name: unzip the file
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: npm install
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user repo
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
