- name: install redis
  hosts: redis
  become: yes
  tasks:
  - name: download rmi repo file
    ansible.builtin.dnf: 
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present

  - name: enable redis 
    ansible.builtin.command: dnf module enable redis:remi-6.2

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: update address
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: start and enable redis
    ansible.builtin.service:
      name: httpd
      state: restarted
      enabled: yes