- name: Install user instance
  hosts: user
  become: yes
  tasks:
  - name: disable and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y;

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: roboshop useradd
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download user file
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unzip user file
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: npm install
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy user repo
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongod.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the categories count
    ansible.builtin.command:  mongo --host 172.31.33.203 --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: product_count

  - name: print the count
    ansible.builtin.debug:
      msg: "product count: {{product_count.stdout}}"

  - name: load user data
    ansible.builtin.command: mongo --host 172.31.33.203 < /app/schema/user.js
    when: product_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes
